[book]
title = "Laconic"
description = "Maximum meaning, minimum tokens."
authors = ["copyleftdev"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/copyleftdev/laconic"
